spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jpa-classic
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
